config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :articles
  resources :artigos

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :body, :category, presence: true
  belongs_to :category
end

app/models/artigo.rb
class Artigo < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :published, :category_id)
    end
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
  before_action :set_artigo, only: [:show, :edit, :update, :destroy]

  # GET /artigos
  # GET /artigos.json
  def index
    @artigos = Artigo.all
  end

  # GET /artigos/1
  # GET /artigos/1.json
  def show
  end

  # GET /artigos/new
  def new
    @artigo = Artigo.new
  end

  # GET /artigos/1/edit
  def edit
  end

  # POST /artigos
  # POST /artigos.json
  def create
    @artigo = Artigo.new(artigo_params)

    respond_to do |format|
      if @artigo.save
        format.html { redirect_to @artigo, notice: 'Artigo was successfully created.' }
        format.json { render :show, status: :created, location: @artigo }
      else
        format.html { render :new }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artigos/1
  # PATCH/PUT /artigos/1.json
  def update
    respond_to do |format|
      if @artigo.update(artigo_params)
        format.html { redirect_to @artigo, notice: 'Artigo was successfully updated.' }
        format.json { render :show, status: :ok, location: @artigo }
      else
        format.html { render :edit }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artigos/1
  # DELETE /artigos/1.json
  def destroy
    @artigo.destroy
    respond_to do |format|
      format.html { redirect_to artigos_url, notice: 'Artigo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artigo
      @artigo = Artigo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artigo_params
      params.require(:artigo).permit(:title, :body, :published_at)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/views/articles/_form.html.slim
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    =f.association :category
    = f.input :body
    = f.input :published

  .form-actions
    = f.button :submit, class: "btn btn-primary"
    '
    = link_to 'Voltar', articles_path, class: "btn btn-default"

app/views/articles/edit.html.slim
h1 Editar Artigo


== render 'form'

app/views/articles/index.html.slim
- @articles = Article.order(:published => :desc)

h1 Lista de Artigos

table.table.tabls-striped
  thead
    tr
      th Título
      th Publicado
      th Categoria
      th       

  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = l article.published, format: :short
        td = article.category.name
        td
          .btn-group.pull-right
            = link_to 'Exibir', article, class: "btn btn-default"
            = link_to 'Editar', edit_article_path(article), class: "btn btn-editar"
            = link_to 'Excluir', article, data: { confirm: 'Tem certeza?' }, method: :delete, class: "btn btn-excluir"

br

= link_to 'Novo Artigo', new_article_path, class: "btn btn-primary"

app/views/articles/new.html.slim
h1 Novo Artigo

== render 'form'

app/views/articles/show.html.slim
- if notice
  .alert.alert-info.alert-dismissible
    button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true" &times;
    = notice
    
.pull-right
  = link_to 'Editar', edit_article_path(@article), class: 'btn btn-editar'
  '
  = link_to 'Voltar', articles_path, class: 'btn btn-default'

h1 = @article.title

hr 
strong = @article.category.name
p = @article.published
= @article.body

app/views/artigos/_form.html.erb
<%= form_for(@artigo) do |f| %>
  <% if @artigo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artigo.errors.count, "error") %> prohibited this artigo from being saved:</h2>

      <ul>
      <% @artigo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artigos/edit.html.erb
<h1>Editing Artigo</h1>

<%= render 'form' %>

<%= link_to 'Show', @artigo %> |
<%= link_to 'Back', artigos_path %>

app/views/artigos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artigos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artigos.each do |artigo| %>
      <tr>
        <td><%= artigo.title %></td>
        <td><%= artigo.body %></td>
        <td><%= artigo.published_at %></td>
        <td><%= link_to 'Show', artigo %></td>
        <td><%= link_to 'Edit', edit_artigo_path(artigo) %></td>
        <td><%= link_to 'Destroy', artigo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artigo', new_artigo_path %>

app/views/artigos/new.html.erb
<h1>New Artigo</h1>

<%= render 'form' %>

<%= link_to 'Back', artigos_path %>

app/views/artigos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @artigo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @artigo.body %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @artigo.published_at %>
</p>

<%= link_to 'Edit', edit_artigo_path(@artigo) %> |
<%= link_to 'Back', artigos_path %>

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Lista de Categorias

table.table.tabls-striped.table-hover
  thead
    tr
      th Nome
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td
          .btn-group.pull-right
            = link_to 'Editar', edit_category_path(category), class: 'btn btn-default'
            '
            = link_to 'Excluir', category, data: { confirm: 'Tem certeza ?' }, method: :delete, class: 'btn btn-default'

br

= link_to 'Nova Categoria', new_category_path, class: 'btn btn-primary btn-sm'

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path

app/views/layouts/application.html.slim
doctype html
html
head
  meta name="viewport" content="width=device-width, initial-scale=1"
  title Papo
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
  = csrf_meta_tags

  /[if lt IE 9]>
    = javascript_include_tag 'html5shiv', 'data-turbolinks-track' => true
    = javascript_include_tag 'respond.min', 'data-turbolinks-track' => true 
body
 .navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      a class="navbar-brand" href="/articles" Papo
      .navbar-collapse
        ul.nav.navbar-nav
          li.active
            a href="/articles" Artigos  
          li
            a href="/categories" Categorias          
 .container
   = yield
 = javascript_include_tag 'application', 'data-turbolinks-track' => true 